ARG NODE_VERSION=20.15.1

# ################################################################################
FROM node:${NODE_VERSION}-alpine AS build

WORKDIR /app

COPY . .

RUN npm i

RUN npm run build

# ################################################################################
FROM nginx:latest AS nginx

COPY --from=build /app/dist /usr/share/nginx/html/

COPY --from=build /app/deployment/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]